//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public int idRegistro { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string horaInicio { get; set; }
        public string horaFinal { get; set; }
        public Nullable<decimal> duracion { get; set; }
        public string titulo { get; set; }
        public string detalles { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string usuarioNombre { get; set; }
        public Nullable<int> empresaId { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
