//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aseguradoras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aseguradoras()
        {
            this.Polizas = new HashSet<Polizas>();
        }
    
        public int aseguradoraId { get; set; }
        public Nullable<int> paisId { get; set; }
        public string aseguradoraNombre { get; set; }
        public string aseguradoraDireccion { get; set; }
        public string aseguradoraWeb { get; set; }
        public string aseguradoraCheque { get; set; }
        public string aseguradoraTelefono { get; set; }
        public string aseguradoraAbreviatura { get; set; }
        public string aseguradoraNIT { get; set; }
    
        public virtual Paises Paises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polizas> Polizas { get; set; }
    }
}
