//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automotores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automotores()
        {
            this.CertificadoAutomotor = new HashSet<CertificadoAutomotor>();
            this.PolizaAutomotorCoberturas = new HashSet<PolizaAutomotorCoberturas>();
        }
    
        public string automotorPlaca { get; set; }
        public Nullable<int> tipoPlacaId { get; set; }
        public Nullable<int> automotorCapacidad { get; set; }
        public Nullable<int> automotorAnio { get; set; }
        public Nullable<int> marcaId { get; set; }
        public Nullable<int> modeloId { get; set; }
        public string automotorColor { get; set; }
        public string automotorNumeroMotor { get; set; }
        public string automotorChasisGrabado { get; set; }
        public string automotorChasisVin { get; set; }
        public string automotoresTipoPropiedad { get; set; }
        public Nullable<int> automotorClaseId { get; set; }
        public string automotorObservaciones { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
    
        public virtual AutomotorClase AutomotorClase { get; set; }
        public virtual AutomotoresMarcas AutomotoresMarcas { get; set; }
        public virtual AutomotoresModelos AutomotoresModelos { get; set; }
        public virtual TipoPlaca TipoPlaca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoAutomotor> CertificadoAutomotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaAutomotorCoberturas> PolizaAutomotorCoberturas { get; set; }
    }
}
