//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoAutomotor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificadoAutomotor()
        {
            this.PolizaAutomotorCoberturas = new HashSet<PolizaAutomotorCoberturas>();
        }
    
        public int certAutoId { get; set; }
        public string certAuto { get; set; }
        public string automotorPlaca { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<int> personaId { get; set; }
        public Nullable<int> clienteCobro { get; set; }
        public Nullable<int> primaId { get; set; }
        public Nullable<int> tipoCertificadoId { get; set; }
        public Nullable<System.DateTime> certAutoFechaIncorporado { get; set; }
        public string certAutoPropietario { get; set; }
        public Nullable<decimal> certAutoDeducible { get; set; }
        public Nullable<decimal> certAutoSumAsegurada { get; set; }
        public Nullable<decimal> certAutoPrima { get; set; }
        public string certAutoClase { get; set; }
        public Nullable<int> certAutoPorcentaje { get; set; }
        public Nullable<decimal> certAutoDescuento { get; set; }
        public Nullable<bool> certAutoEstado { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
    
        public virtual Automotores Automotores { get; set; }
        public virtual Certificados Certificados { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Personas Personas1 { get; set; }
        public virtual Primas Primas { get; set; }
        public virtual Polizas Polizas { get; set; }
        public virtual TipoCertificado TipoCertificado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaAutomotorCoberturas> PolizaAutomotorCoberturas { get; set; }
    }
}
