//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Certificados()
        {
            this.Exclusiones = new HashSet<Exclusiones>();
            this.Reclamos = new HashSet<Reclamos>();
        }
    
        public int certificadosId { get; set; }
        public string certificadosTipo { get; set; }
        public string certificado { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
        public Nullable<bool> certificadoExcluido { get; set; }
        public string numPoliza { get; set; }
    
        public virtual BienesAsegurados BienesAsegurados { get; set; }
        public virtual CertificadoAutomotor CertificadoAutomotor { get; set; }
        public virtual CertificadoPersona CertificadoPersona { get; set; }
        public virtual CertificadoTransporte CertificadoTransporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exclusiones> Exclusiones { get; set; }
        public virtual Inmuebles Inmuebles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamos> Reclamos { get; set; }
    }
}
