//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoPersonaBeneficiario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificadoPersonaBeneficiario()
        {
            this.Reclamos = new HashSet<Reclamos>();
        }
    
        public int certPBeneficiarioId { get; set; }
        public Nullable<int> certPersonaId { get; set; }
        public string certPBeneficiarioNombre { get; set; }
        public Nullable<System.DateTime> certPBeneficiarioFechaNacimiento { get; set; }
        public string certPBeneficiarioSexo { get; set; }
        public Nullable<int> certPBeneficiarioPorcentaje { get; set; }
        public Nullable<bool> certPBeneficiarioEstado { get; set; }
        public Nullable<System.DateTime> certPBeneficiarioFechaInactividad { get; set; }
        public Nullable<int> personaId { get; set; }
        public Nullable<int> tipoBeneficiarioId { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
    
        public virtual CertificadoPersona CertificadoPersona { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual TipoBeneficiario TipoBeneficiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamos> Reclamos { get; set; }
    }
}
