//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoTransporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificadoTransporte()
        {
            this.PolizaTransporteCoberturas = new HashSet<PolizaTransporteCoberturas>();
            this.TransporteDetalleFacturas = new HashSet<TransporteDetalleFacturas>();
            this.PolizaTransporteDocumento = new HashSet<PolizaTransporteDocumento>();
        }
    
        public int transporteId { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<int> tipoCertificadoId { get; set; }
        public Nullable<int> personaId { get; set; }
        public string transporteNoDocumento { get; set; }
        public string transporteOrigen { get; set; }
        public string transporteDestino { get; set; }
        public string tipoTransporte { get; set; }
        public string transTransportador { get; set; }
        public string transConsignador { get; set; }
        public string transDespachador { get; set; }
        public string transDocumentosLegales { get; set; }
        public string transMercaderia { get; set; }
        public Nullable<decimal> transValor { get; set; }
        public Nullable<decimal> transGastos { get; set; }
        public Nullable<decimal> transDeducible { get; set; }
        public Nullable<int> transPorcentaje { get; set; }
        public Nullable<decimal> transTotal { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
    
        public virtual Certificados Certificados { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual TipoCertificado TipoCertificado { get; set; }
        public virtual Polizas Polizas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaTransporteCoberturas> PolizaTransporteCoberturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransporteDetalleFacturas> TransporteDetalleFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaTransporteDocumento> PolizaTransporteDocumento { get; set; }
    }
}
