//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadoPersona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CertificadoPersona()
        {
            this.CertificadoPersonaBeneficiario = new HashSet<CertificadoPersonaBeneficiario>();
        }
    
        public int certPersonaId { get; set; }
        public string certPersona { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<int> personaId { get; set; }
        public Nullable<int> tipoCertificadoId { get; set; }
        public Nullable<int> tipoCategoriaId { get; set; }
        public Nullable<System.DateTime> certPersonaFechaIncorporado { get; set; }
        public Nullable<decimal> certPersonaDeducible { get; set; }
        public Nullable<decimal> certPersonaPrima { get; set; }
        public Nullable<decimal> certPersonaSumaAsegurada { get; set; }
        public string certPersonaObservaciones { get; set; }
        public Nullable<bool> certPersonaEstado { get; set; }
        public Nullable<int> primaId { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
    
        public virtual Certificados Certificados { get; set; }
        public virtual Primas Primas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoPersonaBeneficiario> CertificadoPersonaBeneficiario { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Polizas Polizas { get; set; }
        public virtual TipoCategoria TipoCategoria { get; set; }
        public virtual TipoCertificado TipoCertificado { get; set; }
    }
}
