//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentos
    {
        public int documentosId { get; set; }
        public string documentosCodigo { get; set; }
        public string documentosNombre { get; set; }
        public string documentosDescripcion { get; set; }
    }
}
