//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresas()
        {
            this.Agenda = new HashSet<Agenda>();
            this.GrupoClientes = new HashSet<GrupoClientes>();
            this.Personas = new HashSet<Personas>();
            this.Polizas = new HashSet<Polizas>();
            this.Ramos = new HashSet<Ramos>();
            this.Reclamos = new HashSet<Reclamos>();
            this.ReclamoDocumento = new HashSet<ReclamoDocumento>();
            this.ReclamoSeguimiento = new HashSet<ReclamoSeguimiento>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int empresaId { get; set; }
        public string empresaNombre { get; set; }
        public string empresaAbreviatura { get; set; }
        public Nullable<System.DateTime> empresaFechaNacimiento { get; set; }
        public string empresaNit { get; set; }
        public string empresaNrc { get; set; }
        public string empresaRepresentanteLegal { get; set; }
        public string empresaDUIRepresentante { get; set; }
        public string empresaActividadEconomica { get; set; }
        public Nullable<int> tipoContribuyenteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agenda> Agenda { get; set; }
        public virtual TipoContribuyentes TipoContribuyentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupoClientes> GrupoClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personas> Personas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polizas> Polizas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ramos> Ramos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamos> Reclamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReclamoDocumento> ReclamoDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReclamoSeguimiento> ReclamoSeguimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
