//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exclusiones
    {
        public int exclusionesId { get; set; }
        public string exclusionesTipo { get; set; }
        public Nullable<int> primaId { get; set; }
        public Nullable<int> certificadoId { get; set; }
        public Nullable<int> certificado { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> fechagrabado { get; set; }
        public string sumario { get; set; }
        public Nullable<decimal> pagado { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
    
        public virtual Certificados Certificados { get; set; }
        public virtual Polizas Polizas { get; set; }
        public virtual Primas Primas { get; set; }
    }
}
