//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoPagos
    {
        public int historicoPagosId { get; set; }
        public Nullable<int> pagoId { get; set; }
        public string comentarios { get; set; }
        public string historicoUsuario { get; set; }
        public string historicoEmpresa { get; set; }
        public Nullable<System.DateTime> historicoFechaGrabado { get; set; }
    }
}
