//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoPoliza
    {
        public int idHistoricoPoliza { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<int> tipoPolizaId { get; set; }
        public string empresa { get; set; }
        public string cliente { get; set; }
        public string ramo { get; set; }
        public string aseguradora { get; set; }
        public string clienteCobro { get; set; }
        public string formaDePago { get; set; }
        public Nullable<int> polizaNumeroPagos { get; set; }
        public Nullable<System.DateTime> polizaFechaDesde { get; set; }
        public Nullable<System.DateTime> polizaFechaHasta { get; set; }
        public Nullable<decimal> polizaSumAsegurada { get; set; }
        public Nullable<decimal> polizaDeducible { get; set; }
        public string polizaObservaciones { get; set; }
        public Nullable<decimal> polizaPrimaTotal { get; set; }
        public string historicoPolizaAccion { get; set; }
        public string historicoPolizaUsuario { get; set; }
        public Nullable<System.DateTime> fechaGuardado { get; set; }
    }
}
