//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoPrima
    {
        public int idHistoricoPrima { get; set; }
        public int primaId { get; set; }
        public string primaTipo { get; set; }
        public string polizaNumero { get; set; }
        public string empresa { get; set; }
        public string cliente { get; set; }
        public string pagador { get; set; }
        public Nullable<System.DateTime> primaVigencia { get; set; }
        public Nullable<System.DateTime> primaVencimiento { get; set; }
        public Nullable<System.DateTime> primaRegistrada { get; set; }
        public Nullable<decimal> primaAsegurada { get; set; }
        public Nullable<decimal> primaDeducible { get; set; }
        public Nullable<decimal> primaPrimaExenta { get; set; }
        public Nullable<decimal> primaPrimaGravada { get; set; }
        public Nullable<decimal> primaPrimaNeta { get; set; }
        public Nullable<decimal> primaGastos { get; set; }
        public Nullable<decimal> primaFraccionados { get; set; }
        public Nullable<decimal> primaIva { get; set; }
        public Nullable<decimal> primaTotal { get; set; }
        public Nullable<int> primaNumPagos { get; set; }
        public string primaObservaciones { get; set; }
        public Nullable<decimal> primaPagado { get; set; }
        public string primaPeriodicidad { get; set; }
        public Nullable<decimal> primaTasa { get; set; }
        public string historicoPrimaAccion { get; set; }
        public string historicoPrimaUsuario { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
    }
}
