//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int pagosId { get; set; }
        public Nullable<int> primaId { get; set; }
        public Nullable<int> pagosCuotaId { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<int> clienteId { get; set; }
        public Nullable<int> pagadorId { get; set; }
        public Nullable<System.DateTime> pagosFecha { get; set; }
        public Nullable<decimal> pagosPrima { get; set; }
        public Nullable<decimal> pagosGastos { get; set; }
        public Nullable<decimal> pagosIva { get; set; }
        public Nullable<decimal> pagosTotal { get; set; }
        public string pagosTipo { get; set; }
        public string pagosObservaciones { get; set; }
        public Nullable<System.DateTime> pagosFechaDocu { get; set; }
        public string pagosNumDoc { get; set; }
        public string pagosBanco { get; set; }
        public Nullable<decimal> pagosValorDoc { get; set; }
        public Nullable<decimal> pagosValorEfectivo { get; set; }
        public Nullable<bool> pagosTipoFiscal { get; set; }
        public string pagosComprobante { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
        public Nullable<bool> pagosEstado { get; set; }
    
        public virtual Personas Personas { get; set; }
        public virtual Personas Personas1 { get; set; }
        public virtual Primas Primas { get; set; }
    }
}
