//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personas()
        {
            this.CertificadoAutomotor = new HashSet<CertificadoAutomotor>();
            this.CertificadoAutomotor1 = new HashSet<CertificadoAutomotor>();
            this.CertificadoPersona = new HashSet<CertificadoPersona>();
            this.CertificadoPersonaBeneficiario = new HashSet<CertificadoPersonaBeneficiario>();
            this.CertificadoTransporte = new HashSet<CertificadoTransporte>();
            this.Pagos = new HashSet<Pagos>();
            this.Pagos1 = new HashSet<Pagos>();
            this.PersonaContactos = new HashSet<PersonaContactos>();
            this.PersonaDirecciones = new HashSet<PersonaDirecciones>();
            this.Personas1 = new HashSet<Personas>();
            this.Polizas = new HashSet<Polizas>();
            this.Polizas1 = new HashSet<Polizas>();
            this.Reclamos = new HashSet<Reclamos>();
        }
    
        public int personaId { get; set; }
        public Nullable<int> empresaId { get; set; }
        public Nullable<int> tipoPersonaId { get; set; }
        public string personaNombre { get; set; }
        public Nullable<System.DateTime> personaFechaNacimiento { get; set; }
        public string personaEstadoCivil { get; set; }
        public string personaCorreoElectronico { get; set; }
        public string personaSexo { get; set; }
        public string personaProfesion { get; set; }
        public string personaTelefono { get; set; }
        public Nullable<bool> personaCliente { get; set; }
        public string personaCliDui { get; set; }
        public string personaCliNit { get; set; }
        public string personaCliActividadEconomica { get; set; }
        public Nullable<int> grupoClienteId { get; set; }
        public Nullable<int> tipoContribuyenteId { get; set; }
        public Nullable<bool> personaEstado { get; set; }
        public Nullable<int> personaEmpresa { get; set; }
        public string personaTelefono2 { get; set; }
        public string personaTelefono3 { get; set; }
        public string personaDireccion { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoAutomotor> CertificadoAutomotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoAutomotor> CertificadoAutomotor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoPersona> CertificadoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoPersonaBeneficiario> CertificadoPersonaBeneficiario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoTransporte> CertificadoTransporte { get; set; }
        public virtual Empresas Empresas { get; set; }
        public virtual GrupoClientes GrupoClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaContactos> PersonaContactos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonaDirecciones> PersonaDirecciones { get; set; }
        public virtual TipoContribuyentes TipoContribuyentes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personas> Personas1 { get; set; }
        public virtual Personas Personas2 { get; set; }
        public virtual TipoPersona TipoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polizas> Polizas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polizas> Polizas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamos> Reclamos { get; set; }
    }
}
