//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaContactos
    {
        public int contactoId { get; set; }
        public Nullable<int> personaId { get; set; }
        public string contactoNombre { get; set; }
        public string contactoEmail { get; set; }
        public string contactoCargo { get; set; }
        public string contactoTelefono { get; set; }
        public string contactoMovil { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
