//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaDirecciones
    {
        public int personaDirId { get; set; }
        public Nullable<int> personaId { get; set; }
        public string personatipoDireccion { get; set; }
        public string personaDireccion { get; set; }
        public string personaMunicipio { get; set; }
        public string personaDepartamento { get; set; }
    
        public virtual Personas Personas { get; set; }
    }
}
