//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaCancelaciones
    {
        public int cancelacionesId { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<System.DateTime> cancelacionesFecha { get; set; }
        public string cancelacionesObservaciones { get; set; }
        public string usuario { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
    
        public virtual Polizas Polizas { get; set; }
    }
}
