//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polizas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Polizas()
        {
            this.BienesAsegurados = new HashSet<BienesAsegurados>();
            this.CertificadoAutomotor = new HashSet<CertificadoAutomotor>();
            this.CertificadoPersona = new HashSet<CertificadoPersona>();
            this.CertificadoTransporte = new HashSet<CertificadoTransporte>();
            this.Cuotas = new HashSet<Cuotas>();
            this.Exclusiones = new HashSet<Exclusiones>();
            this.Inmuebles = new HashSet<Inmuebles>();
            this.PolizaAutomotorCoberturas = new HashSet<PolizaAutomotorCoberturas>();
            this.PolizaCancelaciones = new HashSet<PolizaCancelaciones>();
            this.PolizaComentarios = new HashSet<PolizaComentarios>();
            this.PolizaDeducibles = new HashSet<PolizaDeducibles>();
            this.PolizaGastosIniciales = new HashSet<PolizaGastosIniciales>();
            this.PolizaTransporteCoberturas = new HashSet<PolizaTransporteCoberturas>();
            this.Primas = new HashSet<Primas>();
            this.Reclamos = new HashSet<Reclamos>();
            this.PolizaTransporteDocumento = new HashSet<PolizaTransporteDocumento>();
        }
    
        public string polizaNumero { get; set; }
        public Nullable<int> tipoPolizaId { get; set; }
        public Nullable<int> empresaId { get; set; }
        public Nullable<int> clienteId { get; set; }
        public Nullable<int> ramoId { get; set; }
        public Nullable<int> aseguradoraId { get; set; }
        public Nullable<int> clienteCobroId { get; set; }
        public Nullable<int> formaDePagoId { get; set; }
        public Nullable<int> tipoEstatusId { get; set; }
        public Nullable<int> polizaNumeroPagos { get; set; }
        public Nullable<System.DateTime> polizaFechaDesde { get; set; }
        public Nullable<System.DateTime> polizaFechaHasta { get; set; }
        public Nullable<decimal> polizaSumAsegurada { get; set; }
        public Nullable<decimal> polizaDeducible { get; set; }
        public string polizaObservaciones { get; set; }
        public Nullable<decimal> polizaSumaActual { get; set; }
        public Nullable<decimal> polizaPrimaTotal { get; set; }
        public Nullable<int> polizaRenovaciones { get; set; }
        public Nullable<bool> tipoEstatus { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
    
        public virtual Aseguradoras Aseguradoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienesAsegurados> BienesAsegurados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoAutomotor> CertificadoAutomotor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoPersona> CertificadoPersona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CertificadoTransporte> CertificadoTransporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cuotas> Cuotas { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exclusiones> Exclusiones { get; set; }
        public virtual FormaDePago FormaDePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inmuebles> Inmuebles { get; set; }
        public virtual Personas Personas { get; set; }
        public virtual Personas Personas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaAutomotorCoberturas> PolizaAutomotorCoberturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaCancelaciones> PolizaCancelaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaComentarios> PolizaComentarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaDeducibles> PolizaDeducibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaGastosIniciales> PolizaGastosIniciales { get; set; }
        public virtual TipoEstatus TipoEstatus1 { get; set; }
        public virtual Ramos Ramos { get; set; }
        public virtual TipoPoliza TipoPoliza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaTransporteCoberturas> PolizaTransporteCoberturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Primas> Primas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reclamos> Reclamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolizaTransporteDocumento> PolizaTransporteDocumento { get; set; }
    }
}
