//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaGastosIniciales
    {
        public int polizaGastosInicialesId { get; set; }
        public Nullable<int> gastoInicialId { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> primaId { get; set; }
    
        public virtual GastoInicial GastoInicial { get; set; }
        public virtual Primas Primas { get; set; }
        public virtual Polizas Polizas { get; set; }
    }
}
