//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaComentarios
    {
        public int comentariosId { get; set; }
        public string polizaNumero { get; set; }
        public string comentarioTipo { get; set; }
        public Nullable<System.DateTime> comentarioFecha { get; set; }
        public string comentario { get; set; }
        public string usuario { get; set; }
        public string usuarioEmpresa { get; set; }
        public Nullable<System.DateTime> grabado { get; set; }
    
        public virtual Polizas Polizas { get; set; }
    }
}
