//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolizaTransporteDocumento
    {
        public int polizaTransporteDocumentoId { get; set; }
        public Nullable<int> transporteId { get; set; }
        public string polizaNumero { get; set; }
        public Nullable<int> tipoDocumentoId { get; set; }
    
        public virtual CertificadoTransporte CertificadoTransporte { get; set; }
        public virtual Polizas Polizas { get; set; }
        public virtual TipoDocumentoLegal TipoDocumentoLegal { get; set; }
    }
}
