//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ramos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ramos()
        {
            this.Polizas = new HashSet<Polizas>();
        }
    
        public int ramoId { get; set; }
        public string ramoDescripcion { get; set; }
        public string ramoSiglas { get; set; }
        public Nullable<int> tipoPolizaId { get; set; }
        public Nullable<int> empresaId { get; set; }
        public Nullable<int> tipoCertificadoId { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polizas> Polizas { get; set; }
        public virtual TipoCertificado TipoCertificado { get; set; }
        public virtual TipoPoliza TipoPoliza { get; set; }
    }
}
