//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReclamoSeguimiento
    {
        public int idReclamoSeguimiento { get; set; }
        public Nullable<int> reclamoId { get; set; }
        public string reclamoNo { get; set; }
        public Nullable<System.DateTime> reclamoSFechaContacto { get; set; }
        public Nullable<int> reclamoSEmpleadoId { get; set; }
        public string reclamoSEmpleado { get; set; }
        public string reclamoSContactoA { get; set; }
        public string reclamoSDescripcion { get; set; }
        public string reclamoSMedioUtilizado { get; set; }
        public string reclamoSObservaciones { get; set; }
        public Nullable<int> empresaId { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaGrabado { get; set; }
        public Nullable<bool> reclamoSAnulado { get; set; }
    
        public virtual Empresas Empresas { get; set; }
        public virtual Reclamos Reclamos { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
