//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransporteDetalleFacturas
    {
        public int detalleFacturaId { get; set; }
        public Nullable<int> transporteId { get; set; }
        public string detalleFacturaNum { get; set; }
        public Nullable<System.DateTime> detalleFacturaFecha { get; set; }
        public Nullable<decimal> detalleFacturaMonto { get; set; }
    
        public virtual CertificadoTransporte CertificadoTransporte { get; set; }
    }
}
