//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.AgendaRegistro = new HashSet<AgendaRegistro>();
            this.HistorialUsuario = new HashSet<HistorialUsuario>();
            this.ReclamoSeguimiento = new HashSet<ReclamoSeguimiento>();
        }
    
        public int usuarioId { get; set; }
        public string usuarioUsername { get; set; }
        public string usuarioPassword { get; set; }
        public string usuarioNombre { get; set; }
        public string usuarioCorreo { get; set; }
        public string usuarioCelular { get; set; }
        public Nullable<bool> usuarioAdmin { get; set; }
        public Nullable<int> tipoEstatusId { get; set; }
        public Nullable<int> empresaId { get; set; }
        public Nullable<int> PuestoFuncionalId { get; set; }
        public Nullable<int> departamentoId { get; set; }
        public string empresaNombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgendaRegistro> AgendaRegistro { get; set; }
        public virtual Empresas Empresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialUsuario> HistorialUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReclamoSeguimiento> ReclamoSeguimiento { get; set; }
        public virtual TipoEstatus TipoEstatus { get; set; }
        public virtual UsuarioDepartamento UsuarioDepartamento { get; set; }
        public virtual UsuarioPuestoFuncional UsuarioPuestoFuncional { get; set; }
    }
}
